---
include:
#  - board: seeeduino_xiao_ble
#    shield: geacon_jis rgbled_adapter
#    snippet: zmk-usb-logging studio-rpc-usb-uart
#    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: seeeduino_xiao_ble
    shield: geacon rgbled_adapter
    snippet: zmk-usb-logging studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: geacon rgbled_adapter
    snippet: zmk-usb-logging studio-rpc-usb-uart
    cmake-args: -DKEYMAP_FILE=../../config/geacon_jis.keymap
    artifact-name: geacon_jis
  - board: seeeduino_xiao_ble
    shield: settings_reset